### PR TITLE
Optimize newline handling for php.ini files

### PR DESCRIPTION
**Pull request by glensc**
This reverts b46074cb396c8bf3c7000e9867ca974dbe72d7d5
from https://github.com/laminas/laminas-continuous-integration-action/pull/13/files

### CODE REVIEW

**Comment by boesing** [comment]
Please change the commit message to a message which reflects this change.

**Comment by weierophinney** [comment]
OMG - thank you! I couldn't figure out why `echo $INI` was omitting newlines, and was unaware that bash treated echoing a variable differently based on whether it was a bare variable or an interpolated one. (zsh treats both cases exactly the same.)

**Comment by glensc** [comment]
@weierophinney install `checkbashisms` tool, install `shellcheck` tool. they typically report all such issues that have weird side effects in shell language.

shell quoting is the first issue that comes up when writing shell scripts.

as i can't believe zsh diverges from standard sh with the echo behavior, i made at test:


```
➔ zsh
glen@rocinante zf1s % a=$(printf "a\nb")
glen@rocinante zf1s % echo $a
a
b
glen@rocinante zf1s % echo "$a"
a
b
```

```
glen@rocinante zf1s % bash
$ a=$(printf "a\nb")
$ echo $a
a b
$
```

learned something myself too!

**Comment by glensc** [comment]
@weierophinney I'm pretty sure you can use zsh in your actions if you want. but then the rest of the world will get confused if sh is not bash.

**Pull request merged**
