### PR TITLE
Add PHP 8.3 support

### PR DESCRIPTION
**Pull request by MauricioFauth**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

Adds support for PHP 8.3.

### CODE REVIEW

**Comment by boesing** [comment]
Nice, thanks! 
I'd like to wait until PHP 8.3 RC1 is released and built by sury (which will be today but no clue when the sury build will provide RC1 tho).

**Comment by boesing** [comment]
https://jenkins.rfc1925.org/view/PHP%20Engine/job/php_php8.3-binaries/

Most probably, a build from `2023-08-31` or later will indicate that RC1 is available.
I try to check that page regularly to see if its available - in case I do miss it, feel free to ping me here.

Thanks for helping us here, thats really appreciated.

**Comment by MauricioFauth** [comment]
> Most probably, a build from `2023-08-31` or later will indicate that RC1 is available. I try to check that page regularly to see if its available - in case I do miss it, feel free to ping me here.

@boesing RC1 packages are available.

**Comment by boesing** [comment]
Huge. lets wait until the build has finished. I'll take care of the rebuild tomorrow or later this evening (CEST). 
Thanks for pinging me ☺️

**Comment by boesing** [comment]
LGTM. Thanks, @MauricioFauth!

**Pull request merged**
