### PR TITLE
Git `safe-directory` fix

### PR DESCRIPTION
**Pull request by gsteel**
Moves git config call for safe.directory from the Dockerfile to the entrypoint

Ref #97

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Let's try this out :crossed_fingers:

**Comment by Ocramius** [comment]
@gsteel I'd need this for `1.20.x` though :|

**Comment by gsteel** [comment]
Sorry - gimme a sec and I'll rebase

**Comment by Ocramius** [comment]
Thanks @gsteel!

**Comment by Ocramius** [comment]
Unsure if it's using old tags, but https://github.com/laminas/laminas-validator/actions/runs/2493781041

**Comment by gsteel** [comment]
The release build borked here… Can you re-trigger?
https://github.com/laminas/laminas-continuous-integration-action/actions/runs/2494485245

**Comment by Ocramius** [comment]
Aha, good catch!

**Pull request merged**
