### PR TITLE
Update sqlsrv extension to 5.11 and add PHP 8.2 support

### PR DESCRIPTION
**Pull request by MauricioFauth**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

- Updates PHP 7.4 to use 5.10.1
- Updates PHP 8.0 to use 5.11.0
- Updates PHP 8.1 to use 5.11.0
- Adds support for PHP 8.2 using 5.11.0

### CODE REVIEW

**Comment by boesing** [comment]
@weierophinney since u have the most expertise regarding SQLsrv, could you have a quick glance on this?
LGTM but I do not interact with SQLsrv in any way 😅

**Comment by boesing** [comment]
@MauricioFauth do you know if this is also available for PHP 8.3 already?

**Comment by MauricioFauth** [comment]
> @MauricioFauth do you know if this is also available for PHP 8.3 already?

There's no version that explicit supports it, according to their change log.
https://github.com/microsoft/msphpsql/releases

**Comment by boesing** [comment]
Lets see when this will be closed: https://github.com/microsoft/msphpsql/issues/1477
We can then create a new release with PHP 8.3 support.

Releasing this for now. Thanks, @MauricioFauth!

**Comment by Asaad-AlSharif** [comment]
any one can Update sqlsrv extension to PHP 8.3 support

**Pull request merged**
