### PR TITLE
Lazy-install Swoole/OpenSwoole extensions

### PR DESCRIPTION
**Pull request by weierophinney**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

This patch modifies how the Swoole and OpenSwoole extensions are installed and enabled, with the goals of:

- Reducing container size
- Installing only what is needed for a particular PHP version
- Keeping or improving CI run time

For some time now, we've been downloading a package that contains pre-built Swoole and OpenSwoole extensions for all PHP versions for which we provide the extension (currently 7.3 - 8.1).
That package is large (> 140MB), and inflates the size of the container needlessly for most CI runs.

I've updated the project that builds the extensions to build and package each extension individually, **per PHP version**.
This patch no longer installs these extensions by default, but instead moves the installation to when a build has requested the extension(s).
At that time, it retrieves the package for the extension and PHP version, extracts it, and then enables the extension.

I've tested locally, and in doing so, uncovered an issue with how we were unpacking "before_script" and "after_script" values from a job, (both of which were causing the `entrypoint.sh` to fail);  I've fixed the issue, and verified that the new approach works by running CI jobs against a checkout of mezzio-swoole, using the following.

```bash
docker run -v $(realpath .):/github/workspace -w=/github/workspace laminas-continuous-integration:testing '{"command":"./vendor/bin/phpunit","php":"8.1","extensions":["inotify","swoole"],"ini":[],"dependencies":"locked"}'
```

(Substituting in different PHP versions and each of "swoole" and "openswoole".)
These tests all ran correctly.
I also ran against other repositories that do not use the extension, and these ran normally.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM.

Note that this is a breaking change though, since we removed swoole.

May want to see which packages depend on it, and may be necessary to bump this to `2.x`? (not sure about it)

**Comment by weierophinney** [comment]
> Note that this is a breaking change though, since we removed swoole.

It's not removing it; it's just changing when the extension is installed. Even before, you had to indicate you wanted to enable it before it would be present in the runtime. With the change here, the capabilities are present when you need them, if you indicate you need the swoole extension to run a job.

Basically, it moves installation to the time that it is enabled, which is exactly the same as it is for other extensions that are installable via apt.

**Comment by weierophinney** [comment]
> May want to see which packages depend on it,

Also, note that in the description, I indicated that I've tested against mezzio/mezzio-swoole, which was the primary reason we included the extension. Works exactly as expected, and, in fact, the environment is ready to run the job faster than it had been before (I measured around 1-2 seconds faster in my runs locally).

**Comment by Ocramius** [comment]
LGTM then :D 🚢 ?

**Comment by weierophinney** [comment]
@boesing Should I cut the 1.22.0 release, or wait for the other improvements you're working on? I can also just merge now, and have you release when ready...

**Pull request merged**
