### PR TITLE
Migrate nodejs installation to recommended by nodesource

### PR DESCRIPTION
**Pull request by boesing**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

See also https://github.com/nodesource/distributions#installation-instructions

### CODE REVIEW

**Comment by boesing** [comment]
There is a 60 seconds `sleep` within the `setup_20.x` script which we used before. So this will most probably safe us at least 60 seconds (if not more, since we installed npm/nodejs in two stages).

**Comment by boesing** [comment]
I only found the 20 seconds sleep, those files are meanwhile removed from that repository but I built a few days ago and have seen 60 seconds.
So IMHO time to migrate:
https://github.com/nodesource/distributions/commit/0c4edf5b54f9670e946fb9c7d6d931865a8fa268#diff-6369c68235f4b48c9ea07b0437bdc8054b8a6ca40cb27b4eee9efb032e578b32R161

**Comment by Xerkus** [comment]
@boesing seems they went back to installation scripts

**Comment by Xerkus** [comment]
@boesing is this change still needed?

**Comment by Xerkus** [comment]
Jeez. Current installation fails silently to register nodesource and then default nodejs 12 is installed.

Yeah, this is needed.

**Pull request merged**
