### PR TITLE
Add composer-normalize

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

* Adds `ergebnis/composer-normalize` as a composer global dependency
* Links the `composer-normalize` bin to `/usr/local/bin/composer-normalize`

### CODE REVIEW

**Review by boesing — APPROVED** [review]
LGTM.

The only thing is, that I actually prefer `phive` when installing such stuff.
The main reason is conflicting dependencies between global required components.

Actually, the `cs2pr` tool does not support phive (yet) but `composer-normalize` does.
Maybe something to consider to contribute to `staabm/annotate-pull-request-from-checkstyle` but thats out-of-scope right now.

**Comment by froschdesign** [comment]
@boesing 
Please remember we do not want any further normalization, this was already done during migration from the Zend packages.

**Comment by boesing** [comment]
@froschdesign So we might close this PR? 🤷🏼‍♂️

**Comment by ghostwriter** [comment]
@boesing yes, that is correct

**Pull request closed without merging**
