### PR TITLE
remove default `--prefer-dist` during `composer install` (#126)

### LINKED ISSUE #126: remove --prefer-dist from composer arguments
### Bug Report

Composer runs with unexpected default argument `--prefer-dist `.

|    Q        |   A
|------------ | ------
| Version(s)  | 1.24.0

#### Summary

composer runs with `--prefer-dist`, which seems to be overriding configuration given in composer.json (preferred-install)

#### Current behavior

Composer seems to run with --prefer-dist as argument. This seems save as that is the stated default.

```
https://github.com/laminas/laminas-continuous-integration-action/blob/1.25.x/entrypoint.sh#L89
```

However adding this option will result in installing *all* packages with prefer source *even* if one configures via composer.json to prefer source for a specific package.

```
"config": {
        "preferred-install": {
            "my-org/*": "source"
        }
    }
```

#### How to reproduce

see https://github.com/basz/standard-projections/runs/8186520753 for an example of this.

Resulting in a missing test files from a different repo from the same org.

https://github.com/basz/standard-projections/runs/8186520753?check_suite_focus=true#step:3:457

A work-around is to add --prefer-source as additional argument which overrides `--prefer-dist`, but that becomes slow pretty.

#### Expected behavior

Composer should install with a minimum of assumptions and let end users choose additional arguments. I would expect --prefer-dist not be added as a default.

### PR DESCRIPTION
**Pull request by basz**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Fixes #126

### CODE REVIEW

**Comment by basz** [comment]
unsure about the branch to make the PR to...

**Comment by Ocramius** [comment]
Should be fine as-is 👍

**Review by Ocramius — APPROVED** [review]
🚢

**Comment by froschdesign** [comment]
@basz 
> unsure about the branch to make the PR to...

See the [contributing guidelines](https://github.com/laminas/.github/blob/9043ac7cc63db5184d83d37035993d4f8d1e5b44/CONTRIBUTING.md) (linked here on GitHub in various places, e.g. below each comment field):

> Which branch should you issue a pull request against?
>
> * For fixes against the stable release, issue the pull request against the release branch matching the minor release you want to fix.
> * For new features, or fixes that introduce new elements to the public API (such as new public methods or properties), issue the pull request against the default branch.

**Pull request merged**
