### PR TITLE
Add ShellCheck to CI

### LINKED ISSUE #27: feat: Linting for bash scripts
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC | yes
| BC Break    | no

#### Summary

With #24, I somehow added [invalid syntax](https://github.com/laminas/laminas-continuous-integration-action/pull/24/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R115) which wasn't detected during review. 
To avoid having such problem again, I'd like to add something [ShellCheck](https://github.com/koalaman/shellcheck) to the CI of this repository (which does not have any till yet) as well as for all other projects which are using the laminas CI tooling.

Not sure if there are better tools to verify the syntax of bash scripts, so feedback is welcome.

### PR DESCRIPTION
**Pull request by Slamdunk**
Close https://github.com/laminas/laminas-continuous-integration-action/issues/27

### CODE REVIEW

**Comment by Slamdunk** [comment]
:rocket: 

image

**Review by glensc — APPROVED** [review]

**Review by boesing — APPROVED** [review]
Hm, I wonder if it would be possible to just add the regular laminas CI workflow to this repository and the matrix automatically detects bash files as it does for Markdown and YAML files.

Not sure if it makes sense to use CI for CI (CIception) but having the ability to check shell scripts in every package would be a cool thing imho.

**Comment by glensc** [comment]
The bike is already invited:
- https://github.com/github/super-linter

it includes GitHub action too.

NOTE: I have not verified or used how it works. it's on my ever-growing to-do list to do so.

**Comment by boesing** [comment]
Oh thats awesome!
I wonder if the `laminas-ci-matrix-action` can also create non-laminas actions (so using existing actions aswell instead of only `laminas-continous-integration-container` actions (which are referring to this component).
Thus, we could generate existing actions like the `github/super-linter` which looks like an official action of github.

**Review by weierophinney — APPROVED** [review]
:ship:

**Comment by weierophinney** [comment]
My feeling is that, for now, we need linting of the entry point to ensure it is valid for each release. For other pieces, I'd argue we do some PoCs, and then come back with an RFC or a PR.

**Pull request merged**
